# Generated by Django 4.2 on 2024-10-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_back_length_product_chest_girth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
